### ISSUE TITLE
请问启动的docker容器里面怎么无法安装n？

### ISSUE THREAD

**Issue by banduoba** [springjk/web-dev-docker#2]
# npm install -g n                                                                                                                                  [21:35:40]
npm info it worked if it ends with ok
npm info using npm@3.10.8
npm info using node@v6.9.1
npm info attempt registry request try #1 at 9:35:46 PM
npm http request GET https://registry.npm.taobao.org/n
npm http 304 https://registry.npm.taobao.org/n
npm info addNameTag [ 'n', 'latest' ]
npm info lifecycle n@2.1.8~preinstall: n@2.1.8
npm info linkStuff n@2.1.8
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
npm info lifecycle n@2.1.8~install: n@2.1.8
npm info lifecycle n@2.1.8~postinstall: n@2.1.8
/usr/local/lib
`-- n@2.1.8

npm info ok

root@7ebdcd5724f5: /workspace
 # n stable                                                                                                                                          [21:35:46]
env: can't execute 'bash': No such file or directory
FAIL

**Comment by springjk** [comment]
没用过这个包，看报错是 `n` 的代码调用了 `bash`, 没有检测 `bash` 不存在的时候去调用 `sh` 或 `zsh`，`alpine` 版的 Linux 是默认不带 `bash` 的，不过为了解决这个问题你可以在容器内执行：
```shell
# 安装 bash
apk update && apk add bash
# 切换到 bash
bash
```

**Comment by banduoba** [comment]
谢谢 按照你说的方法确实可以安装上 `n`了

**Comment by banduoba** [comment]
不过进一步安装node版本的时候遇到如下问题：
`bash-4.3# n stable

     install : node-v8.6.0
       mkdir : /usr/local/n/versions/node/8.6.0
       fetch : https://nodejs.org/dist/v8.6.0/node-v8.6.0-linux-x64.tar.gz
tar: unrecognized option: strip-components=1
BusyBox v1.24.2 (2016-08-12 14:38:34 GMT) multi-call binary.
Usage: tar -[cxtZzJjahmvO] [-X FILE] [-T FILE] [-f TARFILE] [-C DIR] [FILE]...
Create, extract, or list files from a tar file
Operation:
	c	Create
	x	Extract
	t	List
	f	Name of TARFILE ('-' for stdin/out)
	C	Change to DIR before operation
	v	Verbose
	Z	(De)compress using compress
	z	(De)compress using gzip
	J	(De)compress using xz
	j	(De)compress using bzip2
	a	(De)compress using lzma
	O	Extract to stdout
	h	Follow symlinks
	m	Don't restore mtime
	exclude	File to exclude
	X	File with names to exclude
	T	File with names to include
curl: (23) Failed writing body (0 != 940)
cp: can't stat '/usr/local/n/versions/node/8.6.0/bin': No such file or directory
cp: can't stat '/usr/local/n/versions/node/8.6.0/lib': No such file or directory
cp: can't stat '/usr/local/n/versions/node/8.6.0/include': No such file or directory
cp: can't stat '/usr/local/n/versions/node/8.6.0/share': No such file or directory
   installed : v6.9.1`

**Comment by springjk** [comment]
`n` 无法运行在 `alpine` 见 [#431](https://github.com/tj/n/issues/431)，我对 Dockerfile 进行了重写，发了两个新的版本，latest 更改为基于 `debian`，系统组件较为齐全，并且自带了 `nvm`，相比 `n` 隔离性更好，需要时也可以自行安装 `n`  
![image](https://user-images.githubusercontent.com/7900609/31808561-4cd4d37a-b5a6-11e7-9544-361e9a689540.png)

替换本地的老镜像方法
```shell
sudo docker pull springjk/webdev
sudo docker rm  -f webdev
sudo docker run -itd --name webdev --restart=always springjk/webdev
sudo docker exec -it webdev zsh
```

**Comment by banduoba** [comment]
非常感谢

**Comment by banduoba** [comment]
不好意思,今天安装试了一下,安装n还是不行,错误和之前提示的一样
`bash-4.3# n stable
cp: can't stat '/usr/local/n/versions/node/8.6.0/bin': No such file or directory
cp: can't stat '/usr/local/n/versions/node/8.6.0/lib': No such file or directory
cp: can't stat '/usr/local/n/versions/node/8.6.0/include': No such file or directory
cp: can't stat '/usr/local/n/versions/node/8.6.0/share': No such file or directory
`

**Comment by banduoba** [comment]
┌─[root@885efd836193] - [/workspace] - [Sun Oct 22, 21:40]
└─[$]> nvm
zsh: command not found: nvm
┌─[root@885efd836193] - [/workspace] - [Sun Oct 22, 21:40]
└─[$]>

**Comment by springjk** [comment]
我这里测试正常，你这个肯定是镜像没有更新到，是否使用了国内镜像，国内镜像经常会出现不更新的情况，特别是阿里的。
```
springjk-PC:~ $ sudo docker images | grep "springjk"
springjk/webdev             latest              230b897e8280        29 minutes ago      404 MB
```
看看你的日期和哈希码，应该是较早的版本。

解决方法：
1. 换成 [daocloud 加速器](https://www.daocloud.io/mirror#accelerator-doc)
2. 拉一个没缓存的标签名， `sudo docker pull springjk/webdev:debian`，后续 `run` 的时候也要加标签哦

**Comment by banduoba** [comment]
那就是阿里云的问题了.
`➜  ~ docker images | grep "springjk"`
`springjk/webdev     latest              dcc9d88583ae        10 months ago       476MB`
我现在改一下

**Comment by banduoba** [comment]
再请教一个问题,这个镜像里面启动了一个node项目的话,想要在我的电脑上访问这个项目,通过http://localhost:8080 访问不到 这个是要本机怎么设置一下么,之前运行的命令为:
`docker run -itd -p 80:8080 -v /Users/meng/Documents/workspace/docker:/workspace --name webdev springjk/webdev`

**Comment by springjk** [comment]
`-p 80:8080` 你这个命令是把宿主机的80端口映射到容器的8080端口，访问本地的8080当然是不行的，访问80就可以打开了。

这里你也可以多映射几个端口，如 `-p 80:80  8000:8000 8080:8080`，删了运行中的容器，重新运行。
