### ISSUE TITLE
请问下我在容器里面启动了一个网站,本地无法访问?

### ISSUE THREAD

**Issue by banduoba** [springjk/web-dev-docker#5]
启动命令如下:
`docker run -itd -p 8080:8080 -v /Users/meng/Documents/admin:/workspace --name wxhp --restart always springjk/webdev`

启动的项目地址:
项目在本地 /Users/meng/Documents/admin
`git clone https://github.com/PanJiaChen/vue-element-admin.git`

在容器内安装依赖
`npm install`
在容器内启动项目
npm run dev

本地无法通过 http://localhost:8080 访问

**Comment by springjk** [comment]
抱歉时隔多年，你这个肯定是启动的不是 8080 端口，需要 -p 实际的端口，这些 docker 基本语法相信你也早都会了。hava a nice day。
